imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: ru

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: false
    globals:
        storage_service: '@app.storage'

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

propel:
    generator:
        defaultConnection: default
        namespaceAutoPackage: true
        targetPackage: model

    runtime:
        defaultConnection: default

    database:
        connections:
            default:
                adapter:    mysql
                user:       %database_user%
                password:   %database_password%
                dsn:        mysql:host=%database_host%;dbname=%database_name%;charset=UTF8

creonit_admin:
    title: "Robot 🙈"

creonit_page:
    controller: AppBundle:Default:page

creonit_mailing:
    from: noreply@localhost
    template: ::mail.html.twig

creonit_user:
    authorization: "@AuthorizationService"